version: '3.4'

services:
  wm:
    image: wm
    build: .
    environment:
      NODE_ENV: development
    ports:
      - 97
      - 9229:9229
    ## set your startup file here
    command: node --inspect=0.0.0.0:9229 index.js